name: Question
description: Form for questions
title: '[Question]: '
labels:
  - question
body:
  - type: textarea
    attributes:
      label: Ask your question here
      placeholder: Write here
    validations:
      required: true
